Repository chaewonni/FreshmanCommunity, pull requests merged in 2024-02, with the labels that each got.

#5 feat: 회원가입, 로그인, 로그아웃, 회원탈퇴 로직 구현해보았습니다.
  README.md
  client/README.md
  server/.gitignore
  server/README.md
  server/build.gradle
  server/gradle/wrapper/gradle-wrapper.properties
  server/gradlew
  server/gradlew.bat
  server/settings.gradle
  server/src/main/java/teamFive/freshmanCommunity/FreshmanCommunityApplication.java
  server/src/main/java/teamFive/freshmanCommunity/SecurityConfig.java
  server/src/main/java/teamFive/freshmanCommunity/api/MemberApiController.java
  server/src/main/java/teamFive/freshmanCommunity/dto/LoginDto.java
  server/src/main/java/teamFive/freshmanCommunity/dto/LoginResponseDto.java
  server/src/main/java/teamFive/freshmanCommunity/dto/SignupDto.java
  server/src/main/java/teamFive/freshmanCommunity/entity/Major.java
  server/src/main/java/teamFive/freshmanCommunity/entity/Member.java
  server/src/main/java/teamFive/freshmanCommunity/repository/MajorRepository.java
  server/src/main/java/teamFive/freshmanCommunity/repository/MemberRepository.java
  server/src/main/java/teamFive/freshmanCommunity/service/MemberService.java
  server/src/main/resources/application.properties
  server/src/main/resources/application.yml
  server/src/test/java/teamFive/freshmanCommunity/FreshmanCommunityApplicationTests.java
Labels: feat, Back-End

#7 feat: 모든 게시물 보여주기
  server/src/main/java/teamFive/freshmanCommunity/api/ArticleApiController.java
  server/src/main/java/teamFive/freshmanCommunity/api/ArticleApiControllerAdvice.java
  server/src/main/java/teamFive/freshmanCommunity/dto/ArticleDto.java
  server/src/main/java/teamFive/freshmanCommunity/entity/Article.java
  server/src/main/java/teamFive/freshmanCommunity/entity/Major.java
  server/src/main/java/teamFive/freshmanCommunity/entity/Member.java
  server/src/main/java/teamFive/freshmanCommunity/exception/NonExistentBoardIdException.java
  server/src/main/java/teamFive/freshmanCommunity/repository/ArticleRepository.java
  server/src/main/java/teamFive/freshmanCommunity/service/ArticleService.java
  server/src/main/resources/application.properties
Labels: Back-End

#9 feat: 회원가입 및 로그인 예외처리 로직 추가했습니다.
  server/src/main/java/teamFive/freshmanCommunity/api/MemberApiController.java
  server/src/main/java/teamFive/freshmanCommunity/exception/DuplicateMemberException.java
  server/src/main/java/teamFive/freshmanCommunity/exception/GlobalExceptionHandler.java
  server/src/main/java/teamFive/freshmanCommunity/exception/IncorrectPasswordException.java
  server/src/main/java/teamFive/freshmanCommunity/exception/MemberNotFoundException.java
  server/src/main/java/teamFive/freshmanCommunity/service/MemberService.java
Labels: feat, Back-End

#10 refactor: Article 에러 핸들러 이름 변경
  server/src/main/java/teamFive/freshmanCommunity/api/ArticleApiControllerAdvice.java
  server/src/main/java/teamFive/freshmanCommunity/exception/BoardNotFoundException.java
  server/src/main/java/teamFive/freshmanCommunity/exception/GlobalExceptionHandler.java
  server/src/main/java/teamFive/freshmanCommunity/service/ArticleService.java
Labels: Back-End

#11 Feat/comment REST API 구현
  server/src/main/java/teamFive/freshmanCommunity/api/CommentApiController.java
  server/src/main/java/teamFive/freshmanCommunity/dto/CommentDto.java
  server/src/main/java/teamFive/freshmanCommunity/entity/Comment.java
  server/src/main/java/teamFive/freshmanCommunity/entity/LikeComment.java
  server/src/main/java/teamFive/freshmanCommunity/exception/BoardNotFoundByIdException.java
  server/src/main/java/teamFive/freshmanCommunity/exception/CommentNotFoundException.java
  server/src/main/java/teamFive/freshmanCommunity/exception/GlobalExceptionHandler.java
  server/src/main/java/teamFive/freshmanCommunity/repository/CommentRepository.java
  server/src/main/java/teamFive/freshmanCommunity/service/CommentService.java
Labels: feat, Back-End, refactor

#13 refactor: LoginResponseDto에 studentId 추가
  server/src/main/java/teamFive/freshmanCommunity/api/MemberApiController.java
  server/src/main/java/teamFive/freshmanCommunity/dto/LoginResponseDto.java
Labels: Back-End, refactor

#17 feat: 전체 코드 리팩토링 및 피드백
  client/.eslintrc.json
  client/.gitignore
  client/.prettierrc.js
  client/.prettierrc.json
  client/package-lock.json
  client/package.json
  client/public/Dropdown.js
  client/public/Modal.js
  client/public/Scroll-to-top.js
  client/public/index.html
  client/public/manifest.json
  client/public/robots.txt
  client/src/App.css
  client/src/App.jsx
  client/src/components/header/Header.jsx
  client/src/components/header/index.js
  client/src/components/index.js
  client/src/components/list/Card.jsx
  client/src/components/list/List.jsx
  client/src/components/list/card.const.js
  client/src/components/list/index.js
  client/src/components/list/list.style.js
  client/src/components/main/Main.jsx
  client/src/components/main/index.js
  client/src/components/menuButton/MenuButton.jsx
  client/src/components/menuButton/index.js
  client/src/components/modal/Modal.jsx
  client/src/components/modal/index.js
  client/src/index.js
  client/src/pages/App.css
  client/src/pages/App.test.tsx
  client/src/pages/App.tsx
  client/src/pages/index.css
  client/src/pages/index.tsx
  client/src/react-app-env.d.ts
  client/src/reportWebVitals.ts
  client/src/setupTests.ts
  client/tsconfig.json
Labels: Front-End

#15 feat: 게시글 생성 로직 추가
  server/src/main/java/teamFive/freshmanCommunity/api/ArticleApiController.java
  server/src/main/java/teamFive/freshmanCommunity/dto/ArticleCreateDto.java
  server/src/main/java/teamFive/freshmanCommunity/dto/ArticleDto.java
  server/src/main/java/teamFive/freshmanCommunity/dto/ArticleReadDto.java
  server/src/main/java/teamFive/freshmanCommunity/dto/LoginResponseDto.java
  server/src/main/java/teamFive/freshmanCommunity/entity/Article.java
  server/src/main/java/teamFive/freshmanCommunity/exception/BoardNotFoundException.java
  server/src/main/java/teamFive/freshmanCommunity/exception/GlobalExceptionHandler.java
  server/src/main/java/teamFive/freshmanCommunity/exception/IllegalArticleIdException.java
  server/src/main/java/teamFive/freshmanCommunity/service/ArticleService.java
Labels: feat, Back-End, refactor

#20 refactor: 멤버 로직 코드 전체 리팩토링
  server/src/main/java/teamFive/freshmanCommunity/api/MemberApiController.java
  server/src/main/java/teamFive/freshmanCommunity/entity/Member.java
  server/src/main/java/teamFive/freshmanCommunity/repository/MajorRepository.java
  server/src/main/java/teamFive/freshmanCommunity/repository/MemberRepository.java
  server/src/main/java/teamFive/freshmanCommunity/service/MemberService.java
Labels: Back-End, refactor

#19 feat: 댓글 좋아요 로직 구현
  server/src/main/java/teamFive/freshmanCommunity/api/LikeCommentApiController.java
  server/src/main/java/teamFive/freshmanCommunity/dto/LikeDto.java
  server/src/main/java/teamFive/freshmanCommunity/entity/Comment.java
  server/src/main/java/teamFive/freshmanCommunity/entity/LikeComment.java
  server/src/main/java/teamFive/freshmanCommunity/entity/Major.java
  server/src/main/java/teamFive/freshmanCommunity/entity/Member.java
  server/src/main/java/teamFive/freshmanCommunity/repository/LikeCommentRepository.java
  server/src/main/java/teamFive/freshmanCommunity/service/LikeCommentService.java
Labels: feat, Back-End, refactor

#27 feat: 조인 컬럼명 수정 및 외래키 제약조건 설정
  server/src/main/java/teamFive/freshmanCommunity/entity/Article.java
  server/src/main/java/teamFive/freshmanCommunity/entity/Comment.java
  server/src/main/java/teamFive/freshmanCommunity/entity/LikeComment.java
Labels: Back-End

#22 feat: 새 card 추가/과 선택 option 기능 구현, UI/코드 포맷 수정, 초기 설정 변경
  client/.eslintrc.json
  client/package.json
  client/public/index.html
  client/src/App.css
  client/src/App.jsx
  client/src/components/header/Header.jsx
  client/src/components/header/Logo.jsx
  client/src/components/list/Card.jsx
  client/src/components/list/list.style.js
  client/src/components/main/Main.jsx
  client/src/components/modal/Modal.jsx
Labels: feat, docs, Front-End, style

#26 feat: comment dto 분리/좋아요 10개 이상인 경우 정렬/createDate의 format 지정
  server/src/main/java/teamFive/freshmanCommunity/api/CommentApiController.java
  server/src/main/java/teamFive/freshmanCommunity/dto/CommentRequestDto.java
  server/src/main/java/teamFive/freshmanCommunity/dto/CommentResponseDto.java
  server/src/main/java/teamFive/freshmanCommunity/entity/Comment.java
  server/src/main/java/teamFive/freshmanCommunity/exception/GlobalExceptionHandler.java
  server/src/main/java/teamFive/freshmanCommunity/exception/NotSameMemberException.java
  server/src/main/java/teamFive/freshmanCommunity/repository/CommentRepository.java
  server/src/main/java/teamFive/freshmanCommunity/service/CommentService.java
Labels: feat, Back-End, refactor

#24 feat: 게시글 하나 조회 로직 추가
  server/src/main/java/teamFive/freshmanCommunity/api/ArticleApiController.java
  server/src/main/java/teamFive/freshmanCommunity/exception/ArticleNotFoundException.java
  server/src/main/java/teamFive/freshmanCommunity/exception/GlobalExceptionHandler.java
  server/src/main/java/teamFive/freshmanCommunity/exception/MajorConflictWithArticleException.java
  server/src/main/java/teamFive/freshmanCommunity/service/ArticleService.java
Labels: feat, Back-End

#25 feat: 게시글 수정 및 삭제 로직 추가
  server/src/main/java/teamFive/freshmanCommunity/api/ArticleApiController.java
  server/src/main/java/teamFive/freshmanCommunity/entity/Article.java
  server/src/main/java/teamFive/freshmanCommunity/exception/ArticleUpdateAccessDeniedException.java
  server/src/main/java/teamFive/freshmanCommunity/exception/GlobalExceptionHandler.java
  server/src/main/java/teamFive/freshmanCommunity/exception/IdConflictWithDtoException.java
  server/src/main/java/teamFive/freshmanCommunity/service/ArticleService.java
Labels: feat, Back-End

#29 feat: 회원 탈퇴 시 회원이 null이 되는 경우를 고려한 dto 수정
  server/src/main/java/teamFive/freshmanCommunity/dto/ArticleDto.java
  server/src/main/java/teamFive/freshmanCommunity/dto/ArticleReadDto.java
  server/src/main/java/teamFive/freshmanCommunity/dto/CommentResponseDto.java
  server/src/main/java/teamFive/freshmanCommunity/dto/MemberInfoDto.java
  server/src/main/java/teamFive/freshmanCommunity/service/CommentService.java
Labels: feat, Back-End

#32 feat: card 클릭 시 모달 구현
  .vscode/settings.json
  client/.eslintrc.json
  client/package-lock.json
  client/src/App.css
  client/src/components/header/Header.jsx
  client/src/components/header/NewCard.jsx
  client/src/components/header/ViewCard.jsx
  client/src/components/list/Card.jsx
  client/src/components/list/card.const.js
  client/src/components/main/Main.jsx
Labels: feat, docs, Front-End, style

#33 fix: 좋아요 10개 이하의 댓글 시간순 정렬
  server/src/main/java/teamFive/freshmanCommunity/repository/CommentRepository.java
Labels: Back-End, fix

#37 feat: card 단건 조회, 댓글 추가
  client/.eslintrc.json
  client/package-lock.json
  client/package.json
  client/src/App.css
  client/src/components/header/ViewCard.jsx
Labels: feat, docs, Front-End

#34 refactor: 멤버, 게시글 전체적인 코드 리팩토링
  server/src/main/java/teamFive/freshmanCommunity/dto/ArticleDto.java
  server/src/main/java/teamFive/freshmanCommunity/dto/CommentResponseDto.java
  server/src/main/java/teamFive/freshmanCommunity/dto/MemberInfoDto.java
  server/src/main/java/teamFive/freshmanCommunity/entity/Member.java
  server/src/main/java/teamFive/freshmanCommunity/exception/GlobalExceptionHandler.java
  server/src/main/java/teamFive/freshmanCommunity/exception/MajorNotFoundException.java
  server/src/main/java/teamFive/freshmanCommunity/repository/ArticleRepository.java
  server/src/main/java/teamFive/freshmanCommunity/service/ArticleService.java
  server/src/main/java/teamFive/freshmanCommunity/service/MemberService.java
Labels: Back-End, refactor

#35 feat: 외래키 제약조건 SET_NULL 추가
  server/src/main/java/teamFive/freshmanCommunity/entity/Article.java
  server/src/main/java/teamFive/freshmanCommunity/entity/Comment.java
  server/src/main/java/teamFive/freshmanCommunity/entity/Member.java
Labels: feat, Back-End

#36 feat: api명세서 포스트맨으로 수정
  README.md
Labels: feat, Back-End

#42 fix: mypage 오류 수정
  client/.eslintrc.json
  client/src/App.jsx
  client/src/apis/mypage.js
  client/src/components/header/Header.jsx
  client/src/components/mypage/Mypage.jsx
  client/src/components/mypage/index.js
Labels: docs, Front-End, fix

#43 fix: mypage, card 단건 조회 오류 수정
  client/package-lock.json
  client/src/App.jsx
  client/src/apis/viewcard.js
  client/src/components/header/ViewCard.jsx
  client/src/components/main/Main.jsx
  client/src/components/mypage/Mypage.jsx
Labels: Front-End, fix

#48 fix: 로그인, 회원가입, 마이페이지 수정
  client/.eslintrc.json
  client/package-lock.json
  client/package.json
  client/src/App.css
  client/src/apis/index.js
  client/src/apis/login.js
  client/src/apis/newcard.js
  client/src/apis/signup.js
  client/src/components/ViewCard/ViewCard.jsx
  client/src/components/header/NewCard.jsx
  client/src/components/login/Login.jsx
  client/src/components/login/login.css
  client/src/components/main/Main.jsx
  client/src/components/mypage/Mypage.jsx
  client/src/components/newCard/NewCard.jsx
  client/src/components/signup/Signup.jsx
  client/src/components/signup/signup.css
  client/src/setupProxy.js
Labels: docs, Front-End, fix
